name: Update data

on:
  schedule:
    - cron: "0 8 * * *"
    
jobs:
  updateData:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        r-version: [4.2.1] 

    steps:
      - name: Check out code
      - uses: actions/checkout@v2
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: ${{ matrix.r-version }}

      - name: Setting up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v1

       - name: Install dependencies
        run: |
          install.packages(c("rtweet", "dplyr", "tibble",
          "stringr", "lubridate"))
        shell: Rscript {0}

      - name: Update data
        run: |
          source("update_data.R")
        shell: Rscript {0} 
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
          
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}