name: Update data

on:
  schedule:
    - cron: "0 8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updatedata:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        r-version: [4.0.2]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      